version: '3'
services:
  db:
    image: mongo:latest
    container_name: app_db
    ports:
      - "27017:27017"
  mongo-express:
    container_name: mongo-express
    links:
      - 'db:mongo'
    ports:
      - '8081:8081'
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_BASICAUTH_USERNAME=user'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=pass'
    image: mongo-express 