version: "3.7"
services:
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
  mongo-express:
    container_name: mongo-express
    links:
      - 'db:mongo'
    ports:
      - '8081:8081'
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_BASICAUTH_USERNAME=user'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=pass'
    image: mongo-express 
  qaservice:
    container_name: qaservice
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        DB_HOST: "mongodb://db:27017"
    depends_on:
      - db
    ports:
    - "8880:8880"
